# Generated by Django 3.2.15 on 2022-08-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Tickets Created'},
        ),
    ]
